### ISSUE TITLE
Get 2019.2/2020.1 hybrid build to boot on hardware

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/loki#2]

**Comment by josephnobes-stfc** [comment]
**Update 12/10/20:** I have been investigating the configuration of u-boot through the use of the specific menuconfig that can be activated by using `petalinux-config -c u-boot`. This exposes many options to configure including the boot command used. Since this command actually utilizes yocto-devtool to create a new u-boot workspace in `components/yocto/sources`, you can also modify the source as long as the remaining steps of the devtool flow are completed to commit changes back to the meta-user layer (commit, `petalinux-build -c u-boot -x update-recipe` and `petalinux-build -c u-boot -x finish`).

Currently the application of changes in the built image seems inconsistent; although some take effect, others (like the distroboot order) do not seem to. Currently, the best option may be to simply replace the boot command with the desired boot method, followed by distroboot as a backup. This is possible in the u-boot menuconfig.
